steps:
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']
  dir: 'frontend'
- name: 'gcr.io/cloud-builders/npm'
  args: ['run', 'build', '--', '--mode', 'staging']
  dir: 'frontend'
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args: ['gsutil', '-m', 'cp', '-R', './dist/*', 'gs://www.googlingual.com']
  dir: 'frontend'
timeout: "1600s"
