steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args: [
    'gcloud', 'functions', 'deploy', 'text-to-speech-service-stg',
    '--entry-point', 'com.googlingual.services.t2s.TextToSpeech',
    '--runtime', 'java11',
    '--timeout', '300',
    '--vpc-connector', 'projects/$GCP_PROJECT/locations/us-central1/connectors/googlingual-connector',
    '--memory', '512MB',
    '--trigger-topic', 'new-text-to-speech-message']
  dir: 'text-to-speech-service'
timeout: "1600s"
