steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args: ['gcloud', 'functions', 'deploy', 'text-to-speech-service', '--entry-point', 'com.googlingual.services.t2s.TextToSpeech', '--runtime', 'java11', '--trigger-topic', 'new-text-to-speech-message']
  dir: 'text-to-speech-service'
timeout: "1600s"
