steps:
- name: 'gcr.io/cloud-builders/mvn'
  args: ['install']
  dir: 'storage-service'
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args: ['gcloud', 'functions', 'deploy', 'storage-service', '--entry-point', 'com.googlingual.services.storage.InitMessage', '--runtime', 'java11', '--trigger-topic', 'new-untranslated-message']
  dir: 'storage-service'
timeout: "1600s"
